<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * Keeps public/.htaccess's hotlink-protection allowed-domain in sync with APP_URL,
 * automatically, on every deploy — so a domain move (like mitavin.a-haque.com ->
 * mitavin.com, which once broke every image on the live site because the allowed
 * domain was hand-typed here and nobody remembered to update it) never needs a code
 * change or a message to a developer again. Just keep APP_URL correct in .env, same
 * as you already must for the app to work correctly in general.
 *
 * Registered in composer.json's post-autoload-dump, so it runs automatically on every
 * `composer install` / `composer update` — i.e. every normal deploy — with no extra
 * manual step.
 *
 * Deliberately does NOT rely on any %{HTTP_HOST}-style self-referencing trick inside
 * the .htaccess rewrite rule itself — two attempts at that were tried and both
 * silently failed on the production LiteSpeed host (the placeholder was never
 * actually substituted, so the rule blocked every request with any referrer at all,
 * regardless of domain). Plain hardcoded domain matching is the one thing confirmed
 * to work reliably there; this command is what keeps that hardcoded value correct
 * without a human having to remember to update it.
 */
class SyncHotlinkDomain extends Command
{
    protected $signature = 'htaccess:sync-domain';

    protected $description = "Rewrite public/.htaccess's hotlink-protection allowed domain to match APP_URL.";

    private const START_MARKER = '# BEGIN hotlink-allowed-domain (auto-generated by `php artisan htaccess:sync-domain` — do not edit by hand, change APP_URL in .env instead)';
    private const END_MARKER = '# END hotlink-allowed-domain';

    public function handle(): int
    {
        $path = public_path('.htaccess');

        if (! file_exists($path)) {
            $this->warn('public/.htaccess not found — nothing to sync.');
            return self::SUCCESS;
        }

        $host = $this->resolveAppUrlHost();

        if (! $host) {
            $this->warn('Could not determine a host from APP_URL — leaving public/.htaccess untouched.');
            return self::SUCCESS;
        }

        $contents = file_get_contents($path);
        $pattern = '#' . preg_quote(self::START_MARKER, '#') . '.*?' . preg_quote(self::END_MARKER, '#') . '#s';

        if (! preg_match($pattern, $contents)) {
            $this->warn('Hotlink-protection markers not found in public/.htaccess — nothing to sync.');
            return self::SUCCESS;
        }

        $escapedHost = addcslashes($host, '.\\');
        $block = self::START_MARKER . "\n"
            . "    RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?{$escapedHost} [NC]\n"
            . '    ' . self::END_MARKER;

        file_put_contents($path, preg_replace($pattern, $block, $contents));

        $this->info("public/.htaccess hotlink-protection domain synced to: {$host}");

        return self::SUCCESS;
    }

    /**
     * Reads APP_URL straight from .env rather than config('app.url') — a stale
     * config cache (bootstrap/cache/config.php from before this deploy) would
     * otherwise silently feed this the PREVIOUS domain, defeating the entire point.
     * Falls back to config() only if .env can't be read at all.
     */
    private function resolveAppUrlHost(): ?string
    {
        $envPath = base_path('.env');

        if (file_exists($envPath) && preg_match('/^APP_URL\s*=\s*(.*)$/m', file_get_contents($envPath), $matches)) {
            $url = trim($matches[1], " \t\n\r\0\x0B\"'");
            $host = parse_url($url, PHP_URL_HOST);
            if ($host) {
                return $host;
            }
        }

        return parse_url((string) config('app.url'), PHP_URL_HOST) ?: null;
    }
}
